
name: model_A

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        make install
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
    - name: Lint with pylint
      run: |
        make lint
    
    
